workerme: node me.js
workerme2: node me2.js
workert: node test.js
workerbc: node bc.js
workerbc2: node bc2.js
workerasf: node asf1.js
workerasf2: node asf2.js
workerasf3: node asf3.js
workerasf4: node asf4.js
workerasf5: node asf5.js
workerasf6: node asf6.js
workerasf7: node asf7.js
workerasf8: node asf8.js
workerasf9: node asf9.js
workerasf10: node asf10.js
workerasf11: node asf11.js
workerasf12: node asf12.js
workerasf13: node asf13.js
workerasf14: node asf14.js
workerasf15: node asf15.js
workerasf16: node asf16.js
workerasf17: node asf17.js
workerasf18: node asf18.js

